 <!--@copyright Copyright (c) 2016 www.magebuzz.com-->
<?php if ($block->isShowUpcomingEvents()) {
    $upcomingEventCollection = $block->getUpcomingEventCollection();
    ?>
    <div class="block block-events">
        <div class="block-title" style="margin: 0 0 20px;">
            <strong style="font-size: 18px; font-weight: 300;"><span>Upcoming Events</span></strong>
        </div>
        <div class="block-content">
            <?php if (count($upcomingEventCollection) > 0) { ?>
                <ul class="upcoming-events">
                    <?php foreach ($upcomingEventCollection as $event) { ?>
                        <li class="item">
                            <a href="<?php echo $block->getEventUrl($event) ?>"
                               title="<?php echo $event->getTitle() ?>"><?php echo $event->getTitle() ?></a>
                        </li>
                    <?php } ?>
                </ul>
            <?php } ?>
        </div>
    </div>
<?php } ?>
