<?php
$eventsJson = $block->getEventJson();
$events = $block->getEventCollection();
?>
<div class="event-index page-products page-events">
    <script type='text/javascript'>
        function viewmode(mode) {
            var url = '<?php echo $block->getUrl('events/index/index'); ?>';
            url = url + 'mode/' + mode;
            window.location.href = url;
        }
    </script>

    <?php 
    $eventCategories = $block->getEventCategories(); 
    $viewMode = $block->getRequest()->getParam('mode', false);
    $currentModeArr = [];
    if ($viewMode) {
        $currentModeArr = ['mode' => $viewMode];
    }
    ?>
    <!--Filter-->
    <div class="box-filter">
        <form id="top-filter" action="<?php $block->getUrl('events/index/index', $currentModeArr); ?>" method="post" >
            <input type="text" name="event" placeholder="Enter Event Name" class="event-search control" value="<?php echo $block->getEventSearch(); ?>" />
            <input type="text" name="location" placeholder="Enter Location (Street or City)" class="location-search control" value="<?php echo $block->getLocationSearch(); ?>" />
            <?php if ($block->getScopeConfig('events/general_setting/allow_filter_by_cat') && count($eventCategories)) { ?>
                <?php $filterCatId = $block->getFilterCatId(); ?>
                <select name="category" class="category-filter control">
                    <option value=""><?php echo __('All Events'); ?></option>
                    <?php foreach ($eventCategories as $category) {
                        $catId = $category->getId();
                        ?>            
                        <option value="<?php echo $catId; ?>" <?php if ($filterCatId == $catId): ?>selected<?php endif; ?>><?php echo $category->getCategoryTitle(); ?></option>
                    <?php } ?>
                </select>
            <?php } ?>
            <button class="search-button action primary" type="submit" title="Search"><?php echo __('Search'); ?></button>
        </form>
    </div>
    
    <!--View Mode Select-->
    <?php
    $configViewMode = $block->getScopeConfig('events/general_setting/view_mode');
    if ($configViewMode == 'list-calendar' || $configViewMode == 'calendar-list') {
        ?>
        <div class="view-mode">
            <label for="category-filter"><?php echo __('View Mode'); ?></label>
            <select name="viewmode" class="viewmode-list control" onchange="viewmode(this.value)">
                <option value="calendar" <?php if ($block->getCurrentMode() == 'calendar') { ?> selected <?php } ?>><?php echo __('Calendar'); ?></option>      
                <option value="list" <?php if ($block->getCurrentMode() == 'list') { ?> selected <?php } ?>><?php echo __('List'); ?></option>      
            </select>
        </div>
    <?php } ?>

    <?php if (count($events)) { ?>
        <?php if ($block->getCurrentMode() == 'calendar') { ?>
        <!--  calendar mode -->
        <div class="class-calendar" id="calendar">
            <!--Quickview-->
            <?php foreach ($events as $event) { ?>
                <div class="event-quickview" data-event_id="<?php echo $event->getId() ?>">
                    <div class="event-image">
                        <a href="<?php echo $block->getEventUrl($event); ?>" title="<?php echo $event->getTitle(); ?>">
                            <img src="<?php echo $block->getAvatarUrl($event); ?>" alt="<?php echo $event->getTitle(); ?>" />
                        </a>
                    </div>
                    <div class="event-info">
                        <p class="event-title">
                            <a href="<?php echo $block->getEventUrl($event); ?>" title="<?php echo $event->getTitle(); ?>"><?php echo $event->getTitle(); ?></a>
                        </p>
                        <div class="desc">
                            <div class="event-time">
                                <label><?php echo __('Time: ') ?></label>
                                <?php echo $block->getFormattedTime($block->convertTimeToLocal($event->getStartTime())) . ' - ' . $block->getFormattedTime($block->convertTimeToLocal($event->getStartTime())); ?>
                            </div>
                            <div class="event-location">
                                <label><?php echo __('Location: ') ?></label>
                                <?php echo $event->getLocation(); ?>
                            </div>
                            <div class="event-desc std">
                                <label><?php echo __('Description: ') ?></label>
                                <?php echo $block->getShortDescription($event); ?>
                            </div>
                        </div>
                        <div class="link-see-more">
                            <a href="<?php echo $block->getAvatarUrl($event); ?>" title="<?php echo $event->getTitle(); ?>" class="link-learn"><?php echo __('See More') ?></a>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
            
            <!--JS for calendar-->
            <?php $locale = $block->getScopeConfig('events/calendar_setting/language'); ?>
            <?php if ($locale != 'en') { ?>
                <?php $jsFile = $locale . '.js'; ?>
                <script src='<?php echo $block->getViewFileUrl('Magebuzz_Events::js/lang/') . $jsFile; ?>'></script>
            <?php } ?>
            <script type='text/javascript'>
                require(['jquery', 'fullcalendar', 'moment'], function($){
                    var $j = $.noConflict();
                    $(document).ready(function() {
                        var date = new Date();
                        var d = date.getDate();
                        var m = date.getMonth();
                        var y = date.getFullYear();
                        var calendar_mode = '';
                        var switchMode = '<?php echo $block->getScopeConfig('events/calendar_setting/allow_switch_mode'); ?>';
                        var defaultMode = '<?php echo $block->getScopeConfig('events/calendar_setting/default_view_mode'); ?>';
                        if (switchMode == 1) {
                            calendar_mode = 'month,agendaWeek,agendaDay';
                        }
                        var events = <?php echo $eventsJson; ?>;
                        $('#calendar').fullCalendar({
                            <?php if ($locale != 'en') { ?>
                                lang: "<?php echo $locale; ?>",
                            <?php } ?>
                            editable: true,
                            displayEventEnd:true,
                            disableDragging: true,
                            header: {
                                left: 'prev,next today',
                                center: 'title',
                                right: calendar_mode
                            },
                            defaultView: defaultMode,
                            eventTextColor: 'white',
                            timeFormat: 'H:mm',
                            events: events,
                            eventMouseover: eventMouseoverFunc,
                            eventMouseout: eventMouseoutFunc
                        });
                        
                        function eventMouseoverFunc(event, jsEvent, view ) {
                            $('.event-quickview[data-event_id="'+event.id+'"]').css({left:jsEvent.clientX,top:jsEvent.clientY}).show();
                        }
                        function eventMouseoutFunc(event, jsEvent, view ) {
                            $('.event-quickview[data-event_id="'+event.id+'"]').hide();
                        }
                        $('.event-quickview').hover(function() {$(this).show()}, function() {$(this).hide()});
                    });
                });
            </script>
            
        <?php } else { ?>
            <!-- list mode -->
            <div class="toolbar toolbar-products"><?php echo $block->getPagerHtml(); ?></div>
            <div class="products wrapper grid products-grid events-list">
                <ol class="products list items product-items" id="events-list">
                    <?php foreach ($events as $event) { ?>
                        <li class="item product product-item" style="margin-left:0;">
                            <div class="product-item-info" data-container="product-grid">
                                <a href="<?php echo $block->getEventUrl($event); ?>" class="product photo product-item-photo" title="<?php echo $event->getTitle(); ?>">
                                    <span class="product-image-container" style="width:240px;">
                                        <span class="product-image-wrapper" style="padding-bottom: 75%;">
                                            <img src="<?php echo $block->getAvatarUrl($event); ?>" class="product-image-photo" alt="<?php echo $event->getTitle(); ?>" />
                                        </span>
                                    </span>
                                </a>
                                <div class="product details product-item-details">
                                    <h3 class="event-title">
                                        <a href="<?php echo $block->getEventUrl($event); ?>" title="<?php echo $event->getTitle(); ?>"><?php echo $event->getTitle(); ?></a>
                                    </h3>
                                    <div class="desc">
                                        <div class="event-time">
                                            <label><?php echo __('Time: ') ?></label>
                                            <?php echo $block->getFormattedTime($block->convertTimeToLocal($event->getStartTime())) . ' - ' . $block->getFormattedTime($block->convertTimeToLocal($event->getStartTime())); ?>
                                        </div>
                                        <div class="event-location">
                                            <label><?php echo __('Location: ') ?></label>
                                            <?php echo $event->getLocation(); ?>
                                        </div>
                                        <div class="event-desc std">
                                            <label><?php echo __('Description: ') ?></label>
                                            <?php echo $block->getShortDescription($event); ?>
                                        </div>
                                    </div>
                                    <div class="link-see-more">
                                        <a href="<?php echo $block->getEventUrl($event); ?>" title="<?php echo $event->getTitle(); ?>" class="link-learn"><?php echo __('See More') ?></a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    <?php } ?>
                </ol>
            </div>
            <div class="toolbar toolbar-products"><?php echo $block->getPagerHtml(); ?></div>

        <?php } ?>	      
    <?php } else { ?>
        <p class="note-msg" style="margin:20px 0;"><?php echo __('There are no events matching the selection.'); ?></p>
    <?php } ?>
</div> 

