<?php
$event = $block->getEvent();
if ($event->getId()) {
    ?>
    <div class="event-details">
        <!--Left-->
        <div class="product media">
            <!--Image-->
            <div class="event-image">
                <img src="<?php echo $block->getAvatarUrl() ?>" alt="<?php echo $event->getTitle(); ?>" />
            </div>
        </div>
        
        <!--Right-->
        <div class="product-info-main">
            <!--Main-->
            <div class="event-main">
                <div class="event-name">
                    <h1><?php echo $event->getTitle(); ?></h1>
                </div>        
                <!--Content-->
                <div class="event-content">
                    <div class="event-time">
                        <label><?php echo __('Time:') ?></label>
                        <?php echo $block->getStartTime(); ?> - <?php echo $block->getEndTime(); ?>	
                    </div>	
                    <div class="event-location">
                        <label><?php echo __('Location:') ?></label>
                        <?php echo $event->getLocation(); ?>
                    </div>
                </div>
                
                <div class="registration">
                    <?php if ($block->getScopeConfig('events/general_setting/show_num_participants')) {
                        ?>
                        <div class="participants">
                            <label><?php echo __('Number of Participant: '); ?></label>
                            <?php
                            if ($event->getNumberOfParticipant() > 0) {
                                echo $event->getNumberOfParticipant();
                            } else {
                                echo '0';
                            }
                            ?>
                        </div>
                        <?php
                    }
                    if ($event->getRegistrationDeadline()) {
                        ?>
                        <div class="deadline">
                            <label><?php echo __('Registration Deadline: '); ?></label>
                            <?php echo $block->getRegistrationDeadline(); ?>
                        </div>
                    <?php } ?>
                    <br>
                    <div class="event-price">
                        <?php if ($event->getPrice() > 0) { ?>
                            <label><?php echo __('Price:'); ?></label>
                            <?php echo $block->getPrice(); ?>

                        <?php } else {
                            ?>
                            <label><?php echo __('Price:'); ?></label> FREE
                        <?php } ?>
                    </div> <br>

                    <div class="register-button">
                        <?php if ($block->getScopeConfig('events/general_setting/allow_send_invitation')) { ?>
                            <a href="#inviteformcontent" class="invite_friend_button" id="invite_friend_button" title="<?php echo __('Invite Friends'); ?>">
                                <?php echo __('Invite Friends'); ?>
                            </a>
                        <?php } ?> 

                        <!--register event-->
                        <?php
                        if ($block->isAllowRegisterEvent()) {
                            if ($event->getPrice() > 0) {
                                ?>              
                                | <a href="<?php echo $block->getAddToCartUrl(); ?>" title="<?php echo __('Buy Ticket'); ?>">
                                    <span><?php echo __('Buy Ticket') ?></span>
                                </a>
                            <?php } else { ?>
                                | <a href="<?php echo $block->getRegisterUrl() ?>" title="<?php echo __('Register'); ?>">
                                    <?php echo __('Register'); ?>
                                </a>
                                <?php
                            }
                        }
                        ?>

                    </div>
                </div>
                <!-- share Link-->
                <?php if ($block->getScopeConfig('events/general_setting/show_social_share')) { ?>
                    <div class="product-social-links">
                        <ul class="sharing-buttons">
                            <li>
                                <a href="http://www.facebook.com/sharer.php?u=<?php echo $block->getEventUrl() ?>" target="_blank">
                                    <img src="<?php echo $block->getViewFileUrl('Magebuzz_Events::images/facebook.png'); ?>" height="32" width="32" alt="Share on Facebook" title="<?php echo __('Share on Facebook');?>" />
                                </a> 

                            </li>
                            <li>
                                <a href="https://plus.google.com/share?url=<?php echo $block->getEventUrl() ?>" target="_blank">
                                    <img src="<?php echo $block->getViewFileUrl('Magebuzz_Events::images/google_plus.png'); ?>" height="32" width="32" alt="Share on Google+" title="<?php echo __('Share on Google+');?>" />
                                </a> 
                            </li>

                            <li>
                                <a href="http://twitter.com/intent/tweet?source=sharethiscom&url=<?php echo $block->getEventUrl() ?>" target="_blank">
                                    <img src="<?php echo $block->getViewFileUrl('Magebuzz_Events::images/twitter.png'); ?>" height="32" width="32" alt="Share on Twitter" title="<?php echo __('Share on Twitter');?>" />
                                </a> 
                            </li>
                            <li>
                                <a href="<?php echo $block->getUrl('events/index/favorite', ['event_id'=>$event->getId(),'action'=>$block->isFavorited()?'remove':'add']) ?>">
                                    <img src="<?php echo $block->getFavoriteImageSrc(); ?>" height="32" width="32" alt="Favorite" title="<?php echo $block->isFavorited()?__('Remove from Favorite'):__('Add to Favorite'); ?>" />
                                </a>
                            </li>
                        </ul>
                    </div>
                <?php } ?>
                <!-- End Share -->
                <!--Description-->
                <div class="event-description">
                    <?php echo $block->escapeHtml($event->getDescription()); ?>        
                </div>
            </div>
        </div>
    </div>

    <?php if ($block->getScopeConfig('events/general_setting/allow_send_invitation')) { ?>
        <div id="inviteformcontent" style="display:none;">            
            <div id="invite_form_header" class="page-title">
                <h2><?php echo __('Invite Friends'); ?></h2>
            </div>
            <form action="<?php echo $block->getUrl('events/index/sendinvitation') ?>" id="event-invite-form" method="post">		
                <input type="hidden" name="event_id" id="event_id" value="<?php echo $event->getId(); ?>" />
                <div class="field first">
                    <label for="yourname" class="required"><?php echo __('Your Name') ?><span class="required"> *</span></label>
                    <div class="input-box">
                        <input type="text" name="yourname" value="" class="input-text required-entry" id="yourname"/>
                    </div>
                </div>
                <div class="field">
                    <label for="friendemail"><?php echo __('Send to') ?> <span class="required"> *</span></label>
                    <div class="input-box">
                        <input type="text" name="friendemail" value="" class="input-text required-entry validate-email" id="friendemail"/>
                    </div>
                </div>
                <div class="field last">
                    <label for="invitemessage"><?php echo __('Message: ') ?></label>
                    <div class="input-box">			
                        <textarea name="invitemessage" rows="5" cols="44"></textarea>
                    </div>
                </div>

                <div class="buttons-set" style="margin-top:0px">
                    <p class="required"><?php echo __('* Required Fields') ?></p>
                    <button class="button" type="submit" id="invite-form-button" title="submit"><span><?php echo __('Send'); ?></span></button>
                </div>
            </form>
        </div>
        <?php
    }
}
?>

<script type="text/javascript">
    require(["jquery", "mage/mage", "fancybox"], function ($) {
        $(document).ready(function () {
            var inviteForm = $('#event-invite-form');
            inviteForm.mage('validation', {});

            $('#invite_friend_button').fancybox({
                helpers: {
                    title: null
                }
            });
        });
    });
</script>
