<!--@copyright Copyright (c) 2016 www.magebuzz.com-->
<div id="event-wishlist">
    <?php
    if ($block->getCustomerId()) {
        $events = $block->getPagedEvents();
        if (count($events) > 0) {
            ?>
            <div class="toolbar"><?php echo $block->getPagerHtml(); ?></div>
            <div class="events-list table-wrapper">
                <table class="event-wishlist-table table table-striped table-hover">
                    <thead>
                        <tr>
                            <th scope="col" class="col no"><?php echo __('No.') ?></th>
                            <th scope="col" class="col event"><?php echo __('Event') ?></th>
                            <th scope="col" class="col description"><?php echo __('Description') ?></th>
                            <th scope="col" class="col status"><?php echo __('Status') ?></th>
                            <th scope="col" class="col action" colspan="3"><?php echo __('Action') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $no = 0;

                        foreach ($events as $event) {
                            $no++;
                            $eventId = $event->getId();
                            $description = $block->getShortDescription($event);
                            $status = ($event->getStatus() == 1) ? 'Enable' : 'Disable';
                            ?>
                            <tr>
                                <td data-th="<?php echo $block->escapeHtml(__('No.')) ?>" class="col no">
                                    <?php echo $no; ?>
                                </td>
                                <td data-th="<?php echo $block->escapeHtml(__('Event')) ?>" class="col event">
                                    <img src="<?php echo $block->getAvatarUrl($event); ?>" width="100px" height="100px"/>
                                    <span><strong><?php echo $event->getTitle(); ?></strong></span>
                                </td>
                                <td data-th="<?php echo $block->escapeHtml(__('Description')) ?>" class="col description">
                                    <?php echo $description; ?>
                                </td>
                                <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="col status">
                                    <?php echo $status; ?>
                                </td>
                                <td data-th="<?php echo $block->escapeHtml(__('Action')) ?>" class="col action">
                                    <a href="<?php echo $block->getUrl('events/index/view', ['event_id' => $eventId]); ?>">View</a>
                                </td>
                                <td data-th="<?php echo $block->escapeHtml(__('Action')) ?>" class="col action">
                                    <a href="<?php echo $block->getUrl('events/register/index', ['event_id' => $eventId]); ?>">Register</a>
                                </td>
                                <td data-th="<?php echo $block->escapeHtml(__('Action')) ?>" class="col action">
                                    <a href="<?php echo $block->getUrl('events/wishlist/delete', ['event_id' => $eventId]); ?>">Delete</a>
                                </td>
                            </tr>
                            <?php
                        }
                        ?>
                    </tbody>
                </table>
            </div>
            <div class="toolbar"><?php echo $block->getPagerHtml(); ?></div>
            <?php
        } else {
            ?>
            <h3>There are no event in your wishlist</h3>
            <?php
        }
    } else {
        ?>
        <h3>You haven't logged in.</h3>
        <?php
    }
    ?>
</div>